export const ipc = {
	MINIMIZE: 'TITLE_BAR_MINIMIZE',
	TOGGLE_MAXIMIZE: 'TITLE_BAR_TOGGLE_MAXIMIZE',
	CLOSE: 'TITLE_BAR_CLOSE',
	IS_FRAMED: 'TITLE_BAR_IS_FRAMED',
	SET_FRAMED: 'TITLE_BAR_SET_FRAMED'
}